Implement header detection optimization

diff --git a/.github/actions/test-khiops-install/action.yml b/.github/actions/test-khiops-install/action.yml
--- a/.github/actions/test-khiops-install/action.yml
+++ b/.github/actions/test-khiops-install/action.yml
@@ -4,6 +4,123 @@ description: Test khiops' detection of installed drivers
 runs:
   using: composite
   steps:
+    - name: Test that the executables are installed (Linux/macOS)
+      # We compute the directory of khiops_env if khiops_env is in the PATH,
+      # otherwise we get this directory from the environment
+      # We call khiops_env a first time to test the calling of _khiopsgetprocnumber
+      # then we play with KHIOPS_PROC_NUMBER:
+      # - with KHIOPS_PROC_NUMBER=2, khiops should not use MPI, we check that KHIOPS_MPI_COMMAND is empty
+      # - with KHIOPS_PROC_NUMBER=8, khiops should use MPI, we check that KHIOPS_MPI_COMMAND is not empty and KHIOPS_MPI_ERROR is empty
+      #
+      # The env var OMPI_MCA_rmaps_base_oversubscribe is for openmpi < 5;
+      # it corresponds to the flag --oversubscribe (Nodes are allowed to be oversubscribed)
+      # The env var PRTE_MCA_rmaps_default_mapping_policy is for openmpi >= 5;
+      # it corresponds to the flag --map-by :OVERSUBSCRIBE (Nodes are allowed to be oversubscribed)
+      # KHIOPS_MPI_VERBOSE is set to true to detect errors from MPI
+      if: runner.os != 'Windows'
+      shell: bash
+      env:
+        # Use more processes than available CPUs: OpenMPI < 5
+        OMPI_MCA_rmaps_base_oversubscribe: true
+        # Use more processes than available CPUs: OpenMPI >= 5
+        PRTE_MCA_rmaps_default_mapping_policy: :oversubscribe
+        KHIOPS_MPI_VERBOSE: true
+      run: |
+        # Compute or get the khiops_env directory
+        if type -P khiops_env &> /dev/null
+        then
+          KHIOPS_ENV_DIR=$(dirname $(type -P khiops_env))
+        elif [[ -n "$CONDA_ENV_BIN_DIR" ]]
+        then
+          KHIOPS_ENV_DIR=$CONDA_ENV_BIN_DIR
+        else
+          echo "::error::This action expects CONDA_ENV_BIN_DIR to be defined"
+          false
+        fi
+        echo
+        echo --- khiops_env directory $KHIOPS_ENV_DIR
+        echo
+        echo --- Khiops environment with KHIOPS_PROC_NUMBER not set
+
+        # khiops_env is not in the path anymore, for Conda environments
+        $KHIOPS_ENV_DIR/khiops_env --env
+        echo
+        export KHIOPS_PROC_NUMBER=2
+        echo --- Khiops environment with KHIOPS_PROC_NUMBER=$KHIOPS_PROC_NUMBER
+        source $KHIOPS_ENV_DIR/khiops_env --env
+        if [ ! -z "$KHIOPS_MPI_COMMAND" ]; 
+        then 
+          echo "::error::MPI is used even though there are only 2 procs available"
+          false
+        fi
+        echo
+        export KHIOPS_PROC_NUMBER=8
+        echo --- Khiops environment with KHIOPS_PROC_NUMBER=$KHIOPS_PROC_NUMBER
+        source $KHIOPS_ENV_DIR/khiops_env --env
+        if [ ! -z "$KHIOPS_MPI_ERROR" ]; 
+        then 
+          echo "::error::Unexpected MPI error: $KHIOPS_MPI_ERROR"
+          false
+        fi
+        if [ -z "$KHIOPS_MPI_COMMAND" ]; 
+        then 
+          echo "::error::KHIOPS_MPI_COMMAND is not set"
+          false
+        fi
+        echo
+        echo --- Khiops environment with the HOME variable unset and KHIOPS_PROC_NUMBER=$KHIOPS_PROC_NUMBER
+        _HOME=$HOME
+        _EXPECTED_HOME=${TMPDIR:-${TEMP:-${TMP:-/tmp}}}
+        unset HOME
+        source $KHIOPS_ENV_DIR/khiops_env --env
+
+        # Fail if KHIOPS_MPI_HOME is not set as expected
+        if [[ "$KHIOPS_MPI_HOME" != "$_EXPECTED_HOME" ]];
+        then
+          echo "::error::KHIOPS_MPI_HOME is not set to $_EXPECTED_HOME"
+          false
+        fi
+        export HOME=$_HOME
+        unset _EXPECTED_HOME
+        unset _HOME
+        echo
+        echo --- Khiops status
+        $KHIOPS_ENV_DIR/khiops -s
+    - name: Test that the executables are installed (windows)
+      if: runner.os == 'Windows'
+      shell: cmd /C call {0}
+      run: |
+        echo.
+        echo --- Khiops environment with KHIOPS_PROC_NUMBER not set
+        call khiops_env --env
+        echo.
+        set KHIOPS_PROC_NUMBER=2
+        echo --- Khiops environment with KHIOPS_PROC_NUMBER=%KHIOPS_PROC_NUMBER%
+        call khiops_env --env
+        call khiops_env
+        if not "%KHIOPS_MPI_COMMAND%". == "". (
+          echo "::error::MPI is used even though there are only 2 procs available"
+          exit 1
+        )
+        set KHIOPS_PROC_NUMBER=8
+        echo.
+        echo --- Khiops environment with KHIOPS_PROC_NUMBER=%KHIOPS_PROC_NUMBER%
+        call khiops_env --env
+        call khiops_env
+        if not "%KHIOPS_MPI_ERROR%".=="". (
+          echo "::error::Unexpected MPI error: %KHIOPS_MPI_ERROR%"
+          exit 1
+        )
+        if "%KHIOPS_MPI_COMMAND%". == "". (
+          echo "::error::KHIOPS_MPI_COMMAND is not set"
+          exit 1
+        )
+        echo.
+        echo --- Khiops status
+        khiops -s
+        echo.
+        echo --- Khiops Coclustering status
+        khiops_coclustering -s
     - name: Check Khiops output [UNIXes]
       # Test if the output of Khiops in the console is as expected (no mpi or java errors)
       # We expect only one line in stdout+stderr when running 'khiops -v'
@@ -11,7 +128,10 @@ runs:
       shell: bash
       env:
         KHIOPS_PROC_NUMBER: 4
+        # Use more processes than available CPUs: OpenMPI < 5
         OMPI_MCA_rmaps_base_oversubscribe: true
+        # Use more processes than available CPUs: OpenMPI >= 5
+        PRTE_MCA_rmaps_default_mapping_policy: :oversubscribe
         KHIOPS_MPI_VERBOSE: true
       run: |
         # Compute or get the khiops_env directory
